[32m2023-05-27 10:28:34 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e9df1e5-444b-4820-b3e5-99d8627b2fc9 - 46532 - LOGS_CAPTURED - Started capturing logs in process (pid: 46532).
[32m2023-05-27 10:28:34 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e9df1e5-444b-4820-b3e5-99d8627b2fc9 - 46532 - wastewater__cdc__cdc_wastewater - STEP_START - Started execution of step "wastewater__cdc__cdc_wastewater".
[32m2023-05-27 10:28:34 -0400[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 2e9df1e5-444b-4820-b3e5-99d8627b2fc9 - 46532 - wastewater__cdc__cdc_wastewater - STEP_FAILURE - Execution of step "wastewater__cdc__cdc_wastewater" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "wastewater__cdc__cdc_wastewater"::

TypeError: get_data() missing 1 required positional argument: 'current_max_date'

Stack Trace:
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 445, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 124, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 118, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/Desktop/Life/personal-projects/COVID/etl/assets/wastewater/get_cdc_wastewater.py", line 33, in get_cdc_wastewater
    results = [get_data(client, offset, DATASET_ID) for offset in offsets]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/Desktop/Life/personal-projects/COVID/etl/assets/wastewater/get_cdc_wastewater.py", line 33, in <listcomp>
    results = [get_data(client, offset, DATASET_ID) for offset in offsets]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0m
