[32m2023-05-27 10:20:49 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d8d9d894-7c75-4dce-ab82-d0007b19dbce - 45154 - LOGS_CAPTURED - Started capturing logs in process (pid: 45154).
[32m2023-05-27 10:20:49 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d8d9d894-7c75-4dce-ab82-d0007b19dbce - 45154 - wastewater__cdc__cdc_wastewater - STEP_START - Started execution of step "wastewater__cdc__cdc_wastewater".
[32m2023-05-27 10:20:50 -0400[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - d8d9d894-7c75-4dce-ab82-d0007b19dbce - 45154 - wastewater__cdc__cdc_wastewater - STEP_FAILURE - Execution of step "wastewater__cdc__cdc_wastewater" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "wastewater__cdc__cdc_wastewater"::

AssertionError: No new records found

Stack Trace:
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 445, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 124, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 118, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/Desktop/Life/personal-projects/COVID/etl/assets/wastewater/get_cdc_wastewater.py", line 32, in get_cdc_wastewater
    offsets = create_offsets(client, DATASET_ID, current_max_date)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/Desktop/Life/personal-projects/COVID/src/wastewater/get_cdc_wastewater.py", line 110, in create_offsets
    assert num_records > 0, 'No new records found'
           ^^^^^^^^^^^^^^^
[0m
