[32m2023-05-27 10:24:05 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - bac1e03c-659d-4f69-8449-642b18c0ed2d - 45466 - LOGS_CAPTURED - Started capturing logs in process (pid: 45466).
[32m2023-05-27 10:24:05 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - bac1e03c-659d-4f69-8449-642b18c0ed2d - 45466 - wastewater__cdc__cdc_wastewater - STEP_START - Started execution of step "wastewater__cdc__cdc_wastewater".
[32m2023-05-27 10:24:05 -0400[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - bac1e03c-659d-4f69-8449-642b18c0ed2d - 45466 - wastewater__cdc__cdc_wastewater - STEP_FAILURE - Execution of step "wastewater__cdc__cdc_wastewater" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "wastewater__cdc__cdc_wastewater"::

AssertionError: No new records found, max date available is 2023-05-09

Stack Trace:
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 445, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 124, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 118, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/Desktop/Life/personal-projects/COVID/etl/assets/wastewater/get_cdc_wastewater.py", line 32, in get_cdc_wastewater
    offsets = create_offsets(client, DATASET_ID, current_max_date)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/Desktop/Life/personal-projects/COVID/src/wastewater/get_cdc_wastewater.py", line 121, in create_offsets
    assert num_records > 0, f'No new records found, max date available is {live_max_date}'
           ^^^^^^^^^^^^^^^
[0m
