[32m2023-05-27 10:27:26 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d42c6424-49e3-4621-8f4e-2ef42383276f - 46424 - LOGS_CAPTURED - Started capturing logs in process (pid: 46424).
[32m2023-05-27 10:27:26 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d42c6424-49e3-4621-8f4e-2ef42383276f - 46424 - wastewater__cdc__cdc_wastewater - STEP_START - Started execution of step "wastewater__cdc__cdc_wastewater".
[32m2023-05-27 10:27:26 -0400[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - d42c6424-49e3-4621-8f4e-2ef42383276f - 46424 - wastewater__cdc__cdc_wastewater - STEP_FAILURE - Execution of step "wastewater__cdc__cdc_wastewater" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "wastewater__cdc__cdc_wastewater"::

NameError: name 'current_max_date' is not defined

Stack Trace:
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 445, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 124, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/mambaforge/envs/covid/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 118, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/Desktop/Life/personal-projects/COVID/etl/assets/wastewater/get_cdc_wastewater.py", line 33, in get_cdc_wastewater
    results = [get_data(client, offset, DATASET_ID) for offset in offsets]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/Desktop/Life/personal-projects/COVID/etl/assets/wastewater/get_cdc_wastewater.py", line 33, in <listcomp>
    results = [get_data(client, offset, DATASET_ID) for offset in offsets]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffb/Desktop/Life/personal-projects/COVID/src/wastewater/get_cdc_wastewater.py", line 23, in get_data
    where=f"reporting_jurisdiction = 'Texas' and date_start > '{current_max_date}'",
                                                                ^^^^^^^^^^^^^^^^
[0m
